### ISSUE TITLE
Joern php parser can not be found

### ISSUE THREAD

**Issue by aalhuz** [octopus-platform/joern#153]
I wanted to test the joern-php on some php code but I could not find the joern parser (converts PHP code using php-ast to csv format). 

If you can point to Joern php praser git repo it would be great.

Thanks

**Comment by malteskoruppa** [comment]
Hi aalhuz,

sorry about that. I am going to commit the joern-php parser very soon. There's a few tweaks I still have to do and I have to write installation instructions as well as a HOWTO. I guarantee it will be online before EuroS&P 2017, which is at the end of April.

**Comment by malteskoruppa** [comment]
Thanks aalhuz, but I'll leave this open until I've taken care of it. :smiley:

**Comment by aalhuz** [comment]
I am very familiar with php-parser and php-ast. So, I wrote my own parser that uses php-ast (version 40) to get the asts and then create the csv files in jexp format. I am matching the csv files with the ones in the sample folder in joern php extension. One thing that was giving me errors is the AST_TOPLEVEL node type. I am not able to get the endlineno for such nodes. 

Any help is appreciated..

**Comment by malteskoruppa** [comment]
It's not as easy as exporting the output of php-ast. There's several custom nodes and properties and a few tweaks necessary to get the CSV files need for Joern. I will upload the parser in about a week.

**Comment by aalhuz** [comment]
Thanks..
I will be waiting for it.

**Comment by malteskoruppa** [comment]
I've uploaded it:
https://github.com/malteskoruppa/phpjoern

It took a bit longer than expected. Back when we started, we used version 10 of php-ast. Support for this version has since been removed from php-ast. I bumped it up to version 30 for now. Later versions are for PHP 7.1 which is not (yet) fully supported. Please note that you will also need the newest version of Joern from the `dev` branch of the repository. I also had to make some changes there.

Let me know how it works for you!

**Comment by aalhuz** [comment]
Thank you so much ..
I will take a look at it..
